apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: "${apiserver_ip}:6443"
    token: "${token}"
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: "${token}"
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  kubeletExtraArgs:
    cloud-provider: aws
  name: NODE_HOSTNAME
