apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "${token}"
    apiServerEndpoint: "${apiserver_ip}:6443"
    unsafeSkipCAVerification: true
nodeRegistration:
  name: NODE_HOSTNAME
  kubeletExtraArgs:
    cloud-provider: aws
